name       : python-sphinxcontrib-websupport
version    : 1.2.4
release    : 7
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-websupport/archive/1.2.4.tar.gz : bdb68fe985dedfda3541183eeb29113c0516fad52687ae739fd7e14dd0557d6a
license    : BSD
component  : programming.python
summary    : Sphinx API for WebApps
description: |
    sphinxcontrib-webuspport provides a Python API to easily integrate Sphinx documentation into your Web application.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
