name       : python-sphinxcontrib-websupport
version    : 1.0.1
release    : 1
source     :
    - https://pypi.python.org/packages/c5/6b/f0630436b931ad4f8331a9399ca18a7d447f0fcc0c7178fb56b1aee68d01/sphinxcontrib-websupport-1.0.1.tar.gz : 7a85961326aa3a400cd4ad3c816d70ed6f7c740acd7ce5d78cd0a67825072eb9
license    : BSD
component  : programming.python
summary    : Sphinx API for WebApps
description: |
    sphinxcontrib-webuspport provides a Python API to easily integrate Sphinx documentation into your Web application.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools  
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    %python_install

